version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    entrypoint: ["./wait-for-mysql.sh", "mysql"]
    command: ["./api"]
    env_file:
      - .env
  mysql:
    container_name: mysql
    build: ./docker/db
    env_file:
      - .env
    ports:
      - "3306:3306"
